chore: Combine Rust CI workflows (#436)
* Combine Rust CI workflows

* Cache compiled deps even on a failed job

diff --git a/.github/workflows/rust.yaml b/.github/workflows/rust.yaml
--- a/.github/workflows/rust.yaml
+++ b/.github/workflows/rust.yaml
@@ -21,36 +21,8 @@ env:
   CARGO_TERM_COLOR: always
 
 jobs:
-  check:
+  combined:
     runs-on: depot-ubuntu-22.04
-    steps:
-      - uses: actions/checkout@v4
-
-      - name: Install rust
-        uses: dtolnay/rust-toolchain@master
-        with:
-          toolchain: stable
-
-      - uses: actions/cache@v4
-        with:
-          path: |
-            ~/.cargo/registry
-             ~/.cargo/git
-             target
-          key: ${ runner.os }-cargo-debug-${{ hashFiles('**/Cargo.lock') }}
-
-      - name: install dependencies
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
-
-      - name: Run cargo check
-        working-directory: backend
-        run: cargo check --no-default-features
-
-  clippy:
-    runs-on: depot-ubuntu-22.04
-
     steps:
       - uses: actions/checkout@v4
 
@@ -58,37 +30,26 @@ jobs:
         uses: dtolnay/rust-toolchain@master
         with:
           toolchain: stable
-          components: clippy
+          components: clippy, rustfmt
 
-      - uses: actions/cache@v4
+      - uses: Swatinem/rust-cache@v2
         with:
-          path: |
-            ~/.cargo/registry
-            ~/.cargo/git
-            target
-          key: ${{ runner.os }}-cargo-debug-${{ hashFiles('**/Cargo.lock') }}
+          workspaces: backend
+          cache-on-failure: true
 
       - name: install dependencies
         run: |
           sudo apt-get update
           sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
 
-      - name: Run clippy
+      - name: Run checks
         working-directory: backend
-        run: cargo clippy -- -D warnings
-
-  format:
-    runs-on: depot-ubuntu-22.04
-
-    steps:
-      - uses: actions/checkout@v4
-
-      - name: Install latest rust
-        uses: dtolnay/rust-toolchain@master
-        with:
-          toolchain: stable
-          components: rustfmt
-
-      - name: Format
-        working-directory: backend
-        run: cargo fmt -- --check
+        run: |
+          set -e
+          cargo check --no-default-features || { echo "cargo check failed"; CHECK_FAILED=1; }
+          cargo clippy -- -D warnings || { echo "cargo clippy failed"; CLIPPY_FAILED=1; }
+          cargo fmt -- --check || { echo "cargo fmt failed"; FMT_FAILED=1; }
+          if [ "$CHECK_FAILED" -o "$CLIPPY_FAILED" -o "$FMT_FAILED" ]; then
+            echo "One or more checks failed."
+            exit 1
+          fi
